version: '3'
services:
  db:
    image: florencelry/nusdevops:mysql
    # build: ./db
    environment:
      MYSQL_DATABASE: nusmoney
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      DATABASE_HOST: db

  app:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: florencelry/nusdevops:latest
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: nusmoney
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
