FROM mysql:latest

#ENV MYSQL_DATABASE nusmoney
#ENV MYSQL_ROOT_PASSWORD password
#ENV MYSQL_USER mysql
#ENV MYSQL_PASSWORD password
#ENV DATABASE_HOST db

COPY ./sql-scripts /docker-entrypoint-initdb.d/